HW-5
otus-kuber-2021-03/xxdeenxx_platform pull request #9
Opened 2021-05-05 18:00 UTC by xxdeenxx

kubernetes-networks

2021-05-05 19:27 UTC, Jasstkn requested changes
Добрый день. Посмотрела домашнее задание - все хорошо, кроме задания с кенари. 
Предоставьте пожалуйста пример его работы и обратите внимание на мой комментарий

2021-05-05 19:27 UTC, Jasstkn commented on kubernetes-networks/canary/http-prod-ing.yaml
> +spec:
для работы кенари необходимо указывать host

2021-05-05 20:01 UTC, xxdeenxx commented on kubernetes-networks/canary/http-prod-ing.yaml
> +spec:
Добрый вечер. Исправил манифест
Проверил ruby скриптом 

counts = Hash.new(0)
1000.times do
  output = `curl -s -H "Host: http-svc.com" http://172.17.255.3 | grep 'pod namespace'`
  counts[output.strip.split.last] += 1
end
puts counts

результат {"canary"=>499, "prod"=>501}

Спасибо за помощь!)

2021-05-06 05:04 UTC, Jasstkn approved these changes
Добрый день! Домашнее задание выполнено верно :)  По поводу сетей в Kubernetes можно говорить и изучать информацию очень долго.  Вот несколько ссылок, которые могут вам пригодиться:

Сравнение различных ingress controller (https://docs.google.com/spreadsheets/d/191WWNpjJ2za6-nbG4ZoUMXMpUK8KlCIosvQB0f-oq3k/htmlview?pru=AAABdXUzyNk*EfaTEydH1ILcjf1bsmKH1w)
Сетевой плагин Calico и примеры его использования (https://medium.com/flant-com/calico-for-kubernetes-networking-792b41e19d69)
Получение подом IP адреса (https://habr.com/ru/company/flant/blog/521406/)
Диаграммы по архитектуре Kubernetes, в том числе и сетевой (https://brennerm.github.io/posts/kubernetes-overview-diagrams.html#networking)

2021-05-06 05:05 UTC, merged